# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/FPGA_Projects/Basys_Master.xdc

# IP: ip/Div/Div.xco
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Div || ORIG_REF_NAME==Div} -quiet] -quiet
